/**
 * Canonical MuseLog Work entity — API-ready unified schema.
 * All surfaces (Home, Library, Journal, Profile, Detail) should
 * resolve through this model rather than duplicating shapes.
 */
export type WorkType = "book" | "movie" | "music";

/** User relationship with a work — single vocabulary across the app. */
export type WorkUserStatus = "want" | "reading" | "finished" | "dropped";

/** @deprecated Use WorkUserStatus */
export type WorkUserState = WorkUserStatus;

export type WorkTimeline = {
  startDate?: string;
  endDate?: string;
  /** Duration in days when both ends are known. */
  duration?: number;
};

export type WorkAiInsights = {
  summary?: string;
  themes?: string[];
  recommendations?: string[];
};

/**
 * Community / provider rating for a Work (not the user's personal rating).
 * Examples: Goodreads 4.1/5, IMDb 8.2/10, Letterboxd 4.0/5.
 * Rendered on the full Work Detail archive page; populated when APIs are wired.
 */
export type ExternalRating = {
  /** Provider key, e.g. "goodreads", "imdb", "letterboxd". */
  source: string;
  /** Raw score on the provider's scale. */
  value: number;
  /** Max of the provider scale (5, 10, …). */
  scale: number;
  /** Optional vote / rating count from the provider. */
  count?: number;
};

export type {
  WorkEnrichment,
  WorkEnrichmentSimilarWork,
  WorkMoodProfile,
} from "@/types/work-enrichment";

import type { WorkEnrichment } from "@/types/work-enrichment";

export type Work = {
  id: string;
  type: WorkType;
  title: string;
  creator: string;
  /** Image URL or legacy gradient class string until assets are remote. */
  coverUrl: string;
  description: string;
  releaseDate?: string;
  genres: string[];
  /**
   * Relationship status — want / reading / finished / dropped.
   * Catalog/import Works may use a default until the user interacts.
   */
  userStatus: WorkUserStatus;
  /**
   * @deprecated Alias of userStatus for transitional call sites.
   * Prefer userStatus.
   */
  userState: WorkUserStatus;
  timeline: WorkTimeline;
  userNotes: string;
  moodTags: string[];
  /** Optional 1–5 rating when finished (or revisited). */
  rating?: number;
  /** Optional short review / reflection. */
  review?: string;
  /** Optional reason when status is dropped. */
  droppedReason?: string;
  /**
   * Optional external community ratings (Goodreads / IMDb / Letterboxd, …).
   * Distinct from personal `rating`. Not populated until APIs are wired.
   */
  externalRatings?: ExternalRating[];
  aiInsights?: WorkAiInsights;
  /**
   * Optional cultural enrichment profile for Detail pages.
   * Generated by `generateWorkEnrichment` — does not replace API fields.
   */
  enrichment?: WorkEnrichment;
  /** Provider key, e.g. "open_library", "tmdb", "spotify". */
  source?: string;
  /** Stable id in the external provider. */
  externalId?: string;
  /** Opaque provider payload / extras for future API use. */
  metadata?: Record<string, unknown>;
};
