import type { Metadata } from "next";
import {
  JetBrains_Mono,
  Libre_Baskerville,
  Lora,
  Noto_Serif_SC,
} from "next/font/google";

import { NavigationWrapper } from "@/components/navigation/navigation-wrapper";
import { MobileNavigation } from "@/components/mobile/MobileNavigation";

import "./globals.css";

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: "400",
  style: "italic",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

/** CJK fallback companion for Lora body text */
const notoSerifSc = Noto_Serif_SC({
  variable: "--font-noto-serif-sc",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh-CN"
      className={`${lora.variable} ${libreBaskerville.variable} ${jetbrainsMono.variable} ${notoSerifSc.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-[#090A0F] font-body">
        <NavigationWrapper>{children}</NavigationWrapper>
        <MobileNavigation />
      </body>
    </html>
  );
}
