import { resolveJournalItemId } from "@/lib/content/bubble-content-bridge";
import type { UserMediaState } from "@/lib/content/user-media-state";
import type { MediaItem } from "@/types/media";

/**
 * Portfolio demo persona: "The Reflective Explorer"
 * Seeds journal + user-media-state on a fresh install only.
 */
export const DEMO_PERSONA_FLAG_KEY = "muselog-demo-persona-v1";
export const DEMO_PERSONA_ID = "reflective-explorer";

export const DEMO_JOURNAL_ENTRIES: MediaItem[] = [
  {
    id: resolveJournalItemId("book-norwegian-wood"),
    type: "book",
    title: "Norwegian Wood",
    creator: "Haruki Murakami",
    cover: "from-emerald-900 via-teal-900 to-slate-950",
    status: "FINISHED",
    rating: 5,
    quote:
      "Sometimes memories arrive like rain — quiet, persistent, impossible to ignore.",
    note: "A quiet journey about loneliness and connection. Left me with a tender ache for youth.",
    tags: ["nostalgic", "quiet", "melancholy", "reflective"],
    moment: "read on a rainy afternoon",
    date: "2026-07-12",
    startDate: "2026-07-01",
    endDate: "2026-07-12",
    journeyColor: "teal",
    duration: 520,
    memories: [],
  },
  {
    id: resolveJournalItemId("movie-perfect-days"),
    type: "movie",
    title: "Perfect Days",
    creator: "Wim Wenders",
    cover: "from-stone-700 via-stone-900 to-neutral-950",
    status: "FINISHED",
    rating: 5,
    quote: "Beauty lives in the ordinary, if you stay still enough to notice.",
    note: "Reverence for small rituals — morning light, cassette tapes, trees against the sky.",
    tags: ["quiet", "calm", "reflective", "gentle"],
    moment: "watched at dusk",
    date: "2026-07-15",
    startDate: "2026-07-15",
    endDate: "2026-07-15",
    journeyColor: "beige",
    duration: 124,
    memories: [],
  },
  {
    id: resolveJournalItemId("music-carrie-and-lowell"),
    type: "music",
    title: "Carrie & Lowell",
    creator: "Sufjan Stevens",
    cover: "from-cyan-900 via-teal-950 to-slate-950",
    status: "FINISHED",
    rating: 5,
    quote: "Grief rendered in the gentlest tones.",
    note: "Listened alone after midnight. Felt like walking home when the city has gone quiet.",
    tags: ["nostalgic", "melancholy", "quiet", "bittersweet"],
    moment: "listened at night",
    date: "2026-07-18",
    startDate: "2026-07-18",
    endDate: "2026-07-18",
    journeyColor: "sage",
    duration: 43,
    memories: [],
  },
  {
    id: resolveJournalItemId("book-kafka-on-the-shore"),
    type: "book",
    title: "Kafka on the Shore",
    creator: "Haruki Murakami",
    cover: "from-indigo-900 via-violet-900 to-slate-950",
    status: "READING",
    rating: 0,
    quote: "Fate and consciousness walk parallel paths.",
    note: "Halfway through — dreamlike and strange in the best way. Taking it slow.",
    tags: ["dreamlike", "curious", "reflective"],
    moment: "reading before bed",
    date: "2026-07-20",
    startDate: "2026-07-14",
    journeyColor: "teal",
    duration: 210,
    memories: [],
  },
  {
    id: resolveJournalItemId("movie-before-sunrise"),
    type: "movie",
    title: "Before Sunrise",
    creator: "Richard Linklater",
    cover: "from-rose-900 via-red-950 to-neutral-950",
    status: "FINISHED",
    rating: 4,
    quote: "Conversation as romance, time as magic.",
    note: "One night in Vienna that somehow feels like a whole season of life.",
    tags: ["nostalgic", "romantic", "warm", "curious"],
    moment: "rewatched on a soft evening",
    date: "2026-07-10",
    startDate: "2026-07-10",
    endDate: "2026-07-10",
    journeyColor: "beige",
    duration: 101,
    memories: [],
  },
  {
    id: resolveJournalItemId("music-blonde"),
    type: "music",
    title: "Blonde",
    creator: "Frank Ocean",
    cover: "from-sky-900 via-blue-950 to-slate-950",
    status: "READING",
    rating: 0,
    quote: "Confession blurred with abstraction.",
    note: "Still living inside these songs — identity, desire, and soft late-night air.",
    tags: ["dreamy", "melancholy", "reflective", "intimate"],
    moment: "on repeat this week",
    date: "2026-07-21",
    startDate: "2026-07-16",
    journeyColor: "sage",
    duration: 60,
    memories: [],
  },
];

function mediaState(
  partial: Omit<UserMediaState, "createdAt" | "updatedAt" | "addedToJournal"> &
    Partial<Pick<UserMediaState, "addedToJournal" | "createdAt" | "updatedAt">>,
): UserMediaState {
  return {
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-22T18:00:00.000Z",
    addedToJournal: true,
    ...partial,
  };
}

export const DEMO_USER_MEDIA_STATE: Record<string, UserMediaState> = {
  "book-norwegian-wood": mediaState({
    mediaKey: "book-norwegian-wood",
    status: "FINISHED",
    progress: 100,
    rating: 5,
    shortReview: "A quiet journey about loneliness and connection.",
    notes: "Rainy afternoons and tender ache.",
    startDate: "2026-07-01",
    endDate: "2026-07-12",
    journeyColor: "teal",
    title: "Norwegian Wood",
    creator: "Haruki Murakami",
    cover: "from-emerald-900 via-teal-900 to-slate-950",
    mediaType: "BOOK",
    quote:
      "Sometimes memories arrive like rain — quiet, persistent, impossible to ignore.",
  }),
  "book-kafka-on-the-shore": mediaState({
    mediaKey: "book-kafka-on-the-shore",
    status: "ONGOING",
    progress: 48,
    notes: "Dreamlike chapters — taking it slowly.",
    startDate: "2026-07-14",
    journeyColor: "teal",
    title: "Kafka on the Shore",
    creator: "Haruki Murakami",
    cover: "from-indigo-900 via-violet-900 to-slate-950",
    mediaType: "BOOK",
    quote: "Fate and consciousness walk parallel paths.",
  }),
  "movie-perfect-days": mediaState({
    mediaKey: "movie-perfect-days",
    status: "FINISHED",
    progress: 100,
    rating: 5,
    shortReview: "Ordinary light made sacred.",
    notes: "Small rituals, cassette tapes, sky through leaves.",
    startDate: "2026-07-15",
    endDate: "2026-07-15",
    journeyColor: "beige",
    title: "Perfect Days",
    creator: "Wim Wenders",
    cover: "from-stone-700 via-stone-900 to-neutral-950",
    mediaType: "MOVIE",
    quote: "Beauty lives in the ordinary, if you stay still enough to notice.",
  }),
  "movie-before-sunrise": mediaState({
    mediaKey: "movie-before-sunrise",
    status: "FINISHED",
    progress: 100,
    rating: 4,
    shortReview: "One night that feels like a season.",
    startDate: "2026-07-10",
    endDate: "2026-07-10",
    journeyColor: "beige",
    title: "Before Sunrise",
    creator: "Richard Linklater",
    cover: "from-rose-900 via-red-950 to-neutral-950",
    mediaType: "MOVIE",
    quote: "Conversation as romance, time as magic.",
  }),
  "music-carrie-and-lowell": mediaState({
    mediaKey: "music-carrie-and-lowell",
    status: "FINISHED",
    progress: 100,
    rating: 5,
    shortReview: "Grief in the gentlest tones.",
    startDate: "2026-07-18",
    endDate: "2026-07-18",
    journeyColor: "sage",
    title: "Carrie & Lowell",
    creator: "Sufjan Stevens",
    cover: "from-cyan-900 via-teal-950 to-slate-950",
    mediaType: "MUSIC",
    quote: "Grief rendered in the gentlest tones.",
  }),
  "music-blonde": mediaState({
    mediaKey: "music-blonde",
    status: "ONGOING",
    progress: 62,
    notes: "Still living inside these songs.",
    startDate: "2026-07-16",
    journeyColor: "sage",
    title: "Blonde",
    creator: "Frank Ocean",
    cover: "from-sky-900 via-blue-950 to-slate-950",
    mediaType: "MUSIC",
    quote: "Confession blurred with abstraction.",
  }),
  "book-the-little-prince": mediaState({
    mediaKey: "book-the-little-prince",
    status: "WANT",
    addedToJournal: false,
    notes: "Waiting for a quiet weekend.",
    title: "The Little Prince",
    creator: "Antoine de Saint-Exupéry",
    cover: "from-amber-800 via-orange-950 to-slate-950",
    mediaType: "BOOK",
    quote: "What is essential is invisible to the eye.",
    updatedAt: "2026-07-19T12:00:00.000Z",
  }),
  "music-for-emma-forever-ago": mediaState({
    mediaKey: "music-for-emma-forever-ago",
    status: "WANT",
    addedToJournal: false,
    title: "For Emma, Forever Ago",
    creator: "Bon Iver",
    cover: "from-slate-700 via-slate-900 to-black",
    mediaType: "MUSIC",
    quote: "Winter solitude in fragile harmonies.",
    updatedAt: "2026-07-17T09:00:00.000Z",
  }),
};
